version: '3.1'
services:
  node:
    build: .
    volumes: 
      - ./logs:/app/logs
      - ./.cache:/app/.cache
    environment:
      - VERBOSE_VAL=true
      - DRYRUN=true
    secrets:
      - api-token

secrets:
  api-token:
    file: secret